const THREE = require('three');
/**
 * Color parameters and material parameters constant. Any material parameters could be stored here
 * @author Yevhen Petrashchuk a.k.a Vaper de kin 2017
 */
let colors = {
    shingleMap: {
        "Heritage Rustic Black": "RusticBlack",
        "Heritage Black Walnut": "BlackWalnut",
        "Heritage Rustic Cedar": "RusticCedar",
        "Heritage Mountain Slate": "MountainSlate",
        "Premier Antique Black": "AntiqueBlack",
        "Premier Buckskin Tan": "BuckskinTan",
        "Premier Driftwood": "Driftwood",
        "Premier Harvest Brown": "HarvestBrown",
        "Premier Oakwood": "Oakwood",
        "Premier Pewter Gray": "PewterGray",
        "Premier Prairie Wood": "PrairieWood",
        "Premier Sherwood Green": "SherwoodGreen",
        "Premier Weathered White": "WeatheredWhite",
        "Premier Weathered Wood": "WeatheredWood"
    },
    metalMap: {
        "Vintage White": "#c3c2c2",
        "Rustic Red": "#954333",
        "Gray": "#929496",
        "Evergreen": "#0b5e4e",
        "Desert Sand": "#b1a998",
        "Coal Black": "#08080b",
        "Galvalume": "roofs/galvalume",
        "White": "#ffffff",
        "Light Stone": "#b7b7a4",
        "Beige": "#aca389",
        "Ivory": "#ebd9b6",
        "Medium Brown": "#5b3e33",
        "Dark Brown": "#21201c",
        "Burgandy": "#45262e",
        "All Steel Red": "#912d0b",
        "High Gloss Red": "#7e1903",
        "Bright Red": "#cc0105",
        "Copper Penny": "#b97246",
        "Weathered Copper": "#4d493c",
        "Forest Green": "#003527",
        "Medium Green": "#547e5d",
        "Dark Blue": "#014566",
        "All Steel Blue": "#486c85",
        "Dark Grey": "#465153",
        "Light Grey": "#868f8c",
        "Koko Brown": "#543e37",
        "Regal White": "#cecdc4",
        "Black": "#000000",
        "ABC Light Stone": "#D4CAAF",
        "ABC Burnished Slate": "#433C36",
        "ABC Ivy Green": "#004837",
        "ABC Saddle Tan": "#B39C7E",
        "ABC Charcoal Gray": "#535151"
    },
    trimMap: {
        "Vintage White": "#c3c2c2",
        "Rustic Red": "#954333",
        "Gray": "#929496",
        "Evergreen": "#0b5e4e",
        "Desert Sand": "#b1a998",
        "Coal Black": "#08080b",
        "Galvalume": "roofs/galvalume",
        "White": "#ffffff",
        "Light Stone": "#b7b7a4",
        "Beige": "#aca389",
        "Ivory": "#ebd9b6",
        "Medium Brown": "#5b3e33",
        "Dark Brown": "#21201c",
        "Burgandy": "#45262e",
        "All Steel Red": "#912d0b",
        "High Gloss Red": "#7e1903",
        "Bright Red": "#cc0105",
        "Copper Penny": "#b97246",
        "Weathered Copper": "#4d493c",
        "Forest Green": "#003527",
        "Medium Green": "#547e5d",
        "Dark Blue": "#014566",
        "All Steel Blue": "#486c85",
        "Dark Grey": "#465153",
        "Light Grey": "#868f8c",
        "Koko Brown": "#543e37",
        "Regal White": "#cecdc4",
        "Black": "#000000",
        "ABC Light Stone": "#D4CAAF",
        "ABC Burnished Slate": "#433C36",
        "ABC Ivy Green": "#004837",
        "ABC Saddle Tan": "#B39C7E",
        "ABC Charcoal Gray": "#535151"
    },
    metalMaterialOptions: {
        side: THREE.DoubleSide,
        reflectivity: 0.15,
        refractionRatio: 0.6,
        specular: 0x0,
        shininess: 10,
        bumpScale: 2,
        normalScale: new THREE.Vector2(2, 2)
    },
    galvalume: 0xb8b8b8// 0xb7c8d0//0x8d9794
};

module.exports = colors;
